Repository ChrisBradford2/Venom-Linux, pull requests merged in 2022-10, with the labels that each got.

#4 Ajouter des applications dynamiquement
  gulpfile.js
  sources/css/index.min.css
  sources/index.html
  sources/js/application_list.js
  sources/js/index.js
  sources/scss/index.scss
Labels: WIP

#17 Linters SCSS et Javascript
  .eslintrc.json
  .github/workflows/node.js.yml
  .stylelintrc
  package-lock.json
  package.json
  sources/css/index.min.css
  sources/js/application_list.js
  sources/js/index.js
  sources/scss/index.scss
Labels: Waiting code review

#9 Ajouter un fichier lorsqu'on clique sur "New file"
  sources/assets/favicon/android-chrome-192x192.png
  sources/assets/favicon/android-chrome-384x384.png
  sources/assets/favicon/apple-touch-icon.png
  sources/assets/favicon/browserconfig.xml
  sources/assets/favicon/favicon-16x16.png
  sources/assets/favicon/favicon-32x32.png
  sources/assets/favicon/favicon.ico
  sources/assets/favicon/mstile-150x150.png
  sources/assets/favicon/safari-pinned-tab.svg
  sources/assets/favicon/site.webmanifest
  sources/assets/icons/calculator.svg
  sources/assets/icons/file.svg
  sources/css/index.min.css
  sources/index.html
  sources/js/application_list.js
  sources/js/index.js
  sources/scss/index.scss
Labels: feature, Waiting code review, Hight

#19 Navbar
  sources/assets/icons/vibration.svg
  sources/css/index.min.css
  sources/index.html
  sources/js/application_list.js
  sources/js/navbar.js
  sources/scss/index.scss
Labels: Waiting code review

#22 12 feature calculatrice
  package-lock.json
  sources/css/calculator.min.css
  sources/index.html
  sources/js/application_list.js
  sources/js/calculator.js
  sources/scss/calculator.scss
Labels: feature, Waiting code review, Hight
